// Egypt's 27 governorates with a representative list of districts/areas
// (neighborhoods, cities, or markaz-level divisions) for each — used to seed
// the `governorates` and `districts` tables. This is not meant to be an
// exhaustive administrative gazetteer; it covers the well-known
// neighborhoods/areas a customer would realistically pick when booking a
// finishing visit. Anything not listed can still be typed manually via the
// "other" option on the booking form.

export const EGYPT_LOCATIONS: {
  nameAr: string;
  nameEn: string;
  districts: { nameAr: string; nameEn: string }[];
}[] = [
  {
    nameAr: "القاهرة",
    nameEn: "Cairo",
    districts: [
      { nameAr: "مدينة نصر", nameEn: "Nasr City" },
      { nameAr: "مصر الجديدة", nameEn: "Heliopolis" },
      { nameAr: "المعادي", nameEn: "Maadi" },
      { nameAr: "الزمالك", nameEn: "Zamalek" },
      { nameAr: "المقطم", nameEn: "Mokattam" },
      { nameAr: "التجمع الخامس", nameEn: "5th Settlement" },
      { nameAr: "التجمع الأول", nameEn: "1st Settlement" },
      { nameAr: "التجمع الثالث", nameEn: "3rd Settlement" },
      { nameAr: "الرحاب", nameEn: "Al Rehab" },
      { nameAr: "مدينتي", nameEn: "Madinaty" },
      { nameAr: "العاصمة الإدارية الجديدة", nameEn: "New Administrative Capital" },
      { nameAr: "حلوان", nameEn: "Helwan" },
      { nameAr: "المرج", nameEn: "El Marg" },
      { nameAr: "عين شمس", nameEn: "Ain Shams" },
      { nameAr: "الزيتون", nameEn: "El Zeitoun" },
      { nameAr: "شبرا", nameEn: "Shubra" },
      { nameAr: "روض الفرج", nameEn: "Rod El Farag" },
      { nameAr: "وسط البلد", nameEn: "Downtown Cairo" },
      { nameAr: "جاردن سيتي", nameEn: "Garden City" },
      { nameAr: "السيدة زينب", nameEn: "El Sayeda Zeinab" },
      { nameAr: "مصر القديمة", nameEn: "Old Cairo" },
      { nameAr: "دار السلام", nameEn: "Dar El Salam" },
      { nameAr: "البساتين", nameEn: "El Basatin" },
      { nameAr: "المطرية", nameEn: "El Matareya" },
      { nameAr: "الزاوية الحمراء", nameEn: "El Zawya El Hamra" },
      { nameAr: "الشروق", nameEn: "El Shorouk" },
      { nameAr: "بدر", nameEn: "Badr City" },
      { nameAr: "العبور", nameEn: "El Obour" },
      { nameAr: "15 مايو", nameEn: "15 May City" },
    ],
  },
  {
    nameAr: "الجيزة",
    nameEn: "Giza",
    districts: [
      { nameAr: "الدقي", nameEn: "Dokki" },
      { nameAr: "المهندسين", nameEn: "Mohandessin" },
      { nameAr: "العجوزة", nameEn: "Agouza" },
      { nameAr: "الهرم", nameEn: "Haram" },
      { nameAr: "فيصل", nameEn: "Faisal" },
      { nameAr: "6 أكتوبر", nameEn: "6th of October City" },
      { nameAr: "الشيخ زايد", nameEn: "Sheikh Zayed City" },
      { nameAr: "أكتوبر الجديدة", nameEn: "New October" },
      { nameAr: "الحصري", nameEn: "El Hosary" },
      { nameAr: "بولاق الدكرور", nameEn: "Boulaq El Dakrour" },
      { nameAr: "إمبابة", nameEn: "Imbaba" },
      { nameAr: "الوراق", nameEn: "El Warraq" },
      { nameAr: "أوسيم", nameEn: "Ausim" },
      { nameAr: "البدرشين", nameEn: "El Badrasheen" },
      { nameAr: "الصف", nameEn: "El Saff" },
      { nameAr: "أطفيح", nameEn: "Atfih" },
      { nameAr: "كرداسة", nameEn: "Kerdasa" },
      { nameAr: "منشأة القناطر", nameEn: "Manshiyet El Qanater" },
    ],
  },
  {
    nameAr: "الإسكندرية",
    nameEn: "Alexandria",
    districts: [
      { nameAr: "سموحة", nameEn: "Smouha" },
      { nameAr: "سيدي جابر", nameEn: "Sidi Gaber" },
      { nameAr: "لوران", nameEn: "Laurent" },
      { nameAr: "ستانلي", nameEn: "Stanley" },
      { nameAr: "رشدي", nameEn: "Roushdy" },
      { nameAr: "المنتزه", nameEn: "El Montaza" },
      { nameAr: "ميامي", nameEn: "Miami" },
      { nameAr: "العصافرة", nameEn: "El Asafra" },
      { nameAr: "سيدي بشر", nameEn: "Sidi Bishr" },
      { nameAr: "العجمي", nameEn: "El Agamy" },
      { nameAr: "برج العرب", nameEn: "Borg El Arab" },
      { nameAr: "المعمورة", nameEn: "El Maamoura" },
      { nameAr: "كرموز", nameEn: "Karmouz" },
      { nameAr: "المنشية", nameEn: "El Mansheya" },
      { nameAr: "محرم بك", nameEn: "Moharam Bek" },
      { nameAr: "العطارين", nameEn: "El Attarin" },
      { nameAr: "الإبراهيمية", nameEn: "El Ibrahimeya" },
      { nameAr: "زيزينيا", nameEn: "Zizinia" },
      { nameAr: "جليم", nameEn: "Gleem" },
    ],
  },
  {
    nameAr: "القليوبية",
    nameEn: "Qalyubia",
    districts: [
      { nameAr: "بنها", nameEn: "Banha" },
      { nameAr: "شبرا الخيمة", nameEn: "Shubra El Kheima" },
      { nameAr: "القناطر الخيرية", nameEn: "El Qanater El Khayreya" },
      { nameAr: "قليوب", nameEn: "Qalyub" },
      { nameAr: "الخانكة", nameEn: "El Khanka" },
      { nameAr: "كفر شكر", nameEn: "Kafr Shukr" },
      { nameAr: "طوخ", nameEn: "Toukh" },
      { nameAr: "شبين القناطر", nameEn: "Shibin El Qanater" },
      { nameAr: "العبور", nameEn: "El Obour" },
    ],
  },
  {
    nameAr: "الشرقية",
    nameEn: "Sharqia",
    districts: [
      { nameAr: "الزقازيق", nameEn: "Zagazig" },
      { nameAr: "العاشر من رمضان", nameEn: "10th of Ramadan City" },
      { nameAr: "بلبيس", nameEn: "Bilbeis" },
      { nameAr: "فاقوس", nameEn: "Faqous" },
      { nameAr: "منيا القمح", nameEn: "Minya El Qamh" },
      { nameAr: "أبو حماد", nameEn: "Abu Hammad" },
      { nameAr: "أبو كبير", nameEn: "Abu Kabir" },
      { nameAr: "ديرب نجم", nameEn: "Diarb Negm" },
      { nameAr: "الإبراهيمية", nameEn: "El Ibrahimeya" },
      { nameAr: "كفر صقر", nameEn: "Kafr Saqr" },
      { nameAr: "الحسينية", nameEn: "El Husseiniya" },
      { nameAr: "ههيا", nameEn: "Hehya" },
      { nameAr: "مشتول السوق", nameEn: "Mashtoul El Souk" },
      { nameAr: "أولاد صقر", nameEn: "Awlad Saqr" },
      { nameAr: "القرين", nameEn: "El Qorein" },
      { nameAr: "صان الحجر", nameEn: "San El Hagar" },
    ],
  },
  {
    nameAr: "الدقهلية",
    nameEn: "Dakahlia",
    districts: [
      { nameAr: "المنصورة", nameEn: "Mansoura" },
      { nameAr: "طلخا", nameEn: "Talkha" },
      { nameAr: "ميت غمر", nameEn: "Mit Ghamr" },
      { nameAr: "دكرنس", nameEn: "Dekernes" },
      { nameAr: "أجا", nameEn: "Aga" },
      { nameAr: "منية النصر", nameEn: "Meniet El Nasr" },
      { nameAr: "السنبلاوين", nameEn: "El Senbellawein" },
      { nameAr: "شربين", nameEn: "Sherbin" },
      { nameAr: "المنزلة", nameEn: "El Manzala" },
      { nameAr: "بلقاس", nameEn: "Belqas" },
      { nameAr: "الجمالية", nameEn: "El Gamaleya" },
      { nameAr: "المطرية", nameEn: "El Matareya" },
      { nameAr: "ميت سلسيل", nameEn: "Mit Salsil" },
      { nameAr: "نبروه", nameEn: "Nabaroh" },
      { nameAr: "تمي الأمديد", nameEn: "Temay El Amdid" },
      { nameAr: "الكردي", nameEn: "El Kurdi" },
      { nameAr: "بني عبيد", nameEn: "Bani Ebeid" },
    ],
  },
  {
    nameAr: "الغربية",
    nameEn: "Gharbia",
    districts: [
      { nameAr: "طنطا", nameEn: "Tanta" },
      { nameAr: "المحلة الكبرى", nameEn: "El Mahalla El Kubra" },
      { nameAr: "كفر الزيات", nameEn: "Kafr El Zayat" },
      { nameAr: "زفتى", nameEn: "Zefta" },
      { nameAr: "السنطة", nameEn: "El Santa" },
      { nameAr: "قطور", nameEn: "Qotour" },
      { nameAr: "بسيون", nameEn: "Basyoun" },
      { nameAr: "سمنود", nameEn: "Samannoud" },
    ],
  },
  {
    nameAr: "المنوفية",
    nameEn: "Monufia",
    districts: [
      { nameAr: "شبين الكوم", nameEn: "Shibin El Kom" },
      { nameAr: "منوف", nameEn: "Menouf" },
      { nameAr: "سرس الليان", nameEn: "Sers El Layyan" },
      { nameAr: "أشمون", nameEn: "Ashmoun" },
      { nameAr: "الباجور", nameEn: "El Bagour" },
      { nameAr: "قويسنا", nameEn: "Quesna" },
      { nameAr: "بركة السبع", nameEn: "Berket El Sabaa" },
      { nameAr: "تلا", nameEn: "Tala" },
      { nameAr: "الشهداء", nameEn: "El Shohada" },
      { nameAr: "السادات", nameEn: "Sadat City" },
    ],
  },
  {
    nameAr: "البحيرة",
    nameEn: "Beheira",
    districts: [
      { nameAr: "دمنهور", nameEn: "Damanhour" },
      { nameAr: "كفر الدوار", nameEn: "Kafr El Dawwar" },
      { nameAr: "رشيد", nameEn: "Rashid" },
      { nameAr: "إدكو", nameEn: "Edku" },
      { nameAr: "أبو المطامير", nameEn: "Abu El Matamir" },
      { nameAr: "أبو حمص", nameEn: "Abu Hummus" },
      { nameAr: "الدلنجات", nameEn: "El Delengat" },
      { nameAr: "المحمودية", nameEn: "El Mahmoudeya" },
      { nameAr: "شبراخيت", nameEn: "Shubrakhit" },
      { nameAr: "إيتاي البارود", nameEn: "Itay El Baroud" },
      { nameAr: "حوش عيسى", nameEn: "Hosh Eissa" },
      { nameAr: "النوبارية الجديدة", nameEn: "New Nubariya" },
      { nameAr: "وادي النطرون", nameEn: "Wadi El Natrun" },
      { nameAr: "كوم حمادة", nameEn: "Kom Hamada" },
      { nameAr: "بدر", nameEn: "Badr (Beheira)" },
    ],
  },
  {
    nameAr: "الإسماعيلية",
    nameEn: "Ismailia",
    districts: [
      { nameAr: "الإسماعيلية", nameEn: "Ismailia City" },
      { nameAr: "فايد", nameEn: "Fayed" },
      { nameAr: "القنطرة شرق", nameEn: "El Qantara Sharq" },
      { nameAr: "القنطرة غرب", nameEn: "El Qantara Gharb" },
      { nameAr: "التل الكبير", nameEn: "El Tal El Kebir" },
      { nameAr: "أبو صوير", nameEn: "Abu Suwir" },
      { nameAr: "القصاصين", nameEn: "El Qassaseen" },
    ],
  },
  {
    nameAr: "بورسعيد",
    nameEn: "Port Said",
    districts: [
      { nameAr: "حي الشرق", nameEn: "El Sharq" },
      { nameAr: "حي العرب", nameEn: "El Arab" },
      { nameAr: "حي المناخ", nameEn: "El Manakh" },
      { nameAr: "حي الضواحي", nameEn: "El Dawahy" },
      { nameAr: "حي الزهور", nameEn: "El Zohour" },
      { nameAr: "بورفؤاد", nameEn: "Port Fouad" },
      { nameAr: "الجميل", nameEn: "El Gamil" },
    ],
  },
  {
    nameAr: "السويس",
    nameEn: "Suez",
    districts: [
      { nameAr: "حي السويس", nameEn: "El Suez District" },
      { nameAr: "حي الأربعين", nameEn: "El Arbaeen" },
      { nameAr: "حي عتاقة", nameEn: "Ataqa" },
      { nameAr: "حي الجناين", nameEn: "El Ganayen" },
      { nameAr: "حي فيصل", nameEn: "Faisal (Suez)" },
    ],
  },
  {
    nameAr: "كفر الشيخ",
    nameEn: "Kafr El Sheikh",
    districts: [
      { nameAr: "كفر الشيخ", nameEn: "Kafr El Sheikh City" },
      { nameAr: "دسوق", nameEn: "Desouk" },
      { nameAr: "فوه", nameEn: "Fuwwah" },
      { nameAr: "مطوبس", nameEn: "Metoubes" },
      { nameAr: "بلطيم", nameEn: "Baltim" },
      { nameAr: "الحامول", nameEn: "El Hamoul" },
      { nameAr: "بيلا", nameEn: "Bella" },
      { nameAr: "الرياض", nameEn: "El Riyad" },
      { nameAr: "سيدي سالم", nameEn: "Sidi Salem" },
      { nameAr: "قلين", nameEn: "Qellin" },
      { nameAr: "الحملول", nameEn: "El Borollos" },
    ],
  },
  {
    nameAr: "دمياط",
    nameEn: "Damietta",
    districts: [
      { nameAr: "دمياط", nameEn: "Damietta City" },
      { nameAr: "رأس البر", nameEn: "Ras El Bar" },
      { nameAr: "فارسكور", nameEn: "Faraskur" },
      { nameAr: "الزرقا", nameEn: "El Zarqa" },
      { nameAr: "كفر سعد", nameEn: "Kafr Saad" },
      { nameAr: "الروضة", nameEn: "El Rawda" },
      { nameAr: "كفر البطيخ", nameEn: "Kafr El Batikh" },
      { nameAr: "عزبة البرج", nameEn: "Ezbet El Borg" },
    ],
  },
  {
    nameAr: "الفيوم",
    nameEn: "Faiyum",
    districts: [
      { nameAr: "الفيوم", nameEn: "Faiyum City" },
      { nameAr: "طامية", nameEn: "Tamiya" },
      { nameAr: "سنورس", nameEn: "Senuris" },
      { nameAr: "إطسا", nameEn: "Itsa" },
      { nameAr: "أبشواي", nameEn: "Abshway" },
      { nameAr: "يوسف الصديق", nameEn: "Youssef El Sediq" },
      { nameAr: "الفيوم الجديدة", nameEn: "New Faiyum" },
    ],
  },
  {
    nameAr: "بني سويف",
    nameEn: "Beni Suef",
    districts: [
      { nameAr: "بني سويف", nameEn: "Beni Suef City" },
      { nameAr: "الواسطى", nameEn: "El Wasta" },
      { nameAr: "ناصر", nameEn: "Nasser" },
      { nameAr: "إهناسيا", nameEn: "Ehnasia" },
      { nameAr: "ببا", nameEn: "Beba" },
      { nameAr: "الفشن", nameEn: "El Fashn" },
      { nameAr: "سمسطا", nameEn: "Somasta" },
      { nameAr: "بني سويف الجديدة", nameEn: "New Beni Suef" },
    ],
  },
  {
    nameAr: "المنيا",
    nameEn: "Minya",
    districts: [
      { nameAr: "المنيا", nameEn: "Minya City" },
      { nameAr: "ملوي", nameEn: "Mallawi" },
      { nameAr: "سمالوط", nameEn: "Samalut" },
      { nameAr: "بني مزار", nameEn: "Beni Mazar" },
      { nameAr: "مطاي", nameEn: "Maghagha" },
      { nameAr: "أبو قرقاص", nameEn: "Abu Qurqas" },
      { nameAr: "ديرمواس", nameEn: "Deir Mawas" },
      { nameAr: "المنيا الجديدة", nameEn: "New Minya" },
    ],
  },
  {
    nameAr: "أسيوط",
    nameEn: "Asyut",
    districts: [
      { nameAr: "أسيوط", nameEn: "Asyut City" },
      { nameAr: "ديروط", nameEn: "Dayrout" },
      { nameAr: "منفلوط", nameEn: "Manfalut" },
      { nameAr: "القوصية", nameEn: "El Qusiya" },
      { nameAr: "أبنوب", nameEn: "Abnub" },
      { nameAr: "أبو تيج", nameEn: "Abou Tig" },
      { nameAr: "ساحل سليم", nameEn: "Sahel Selim" },
      { nameAr: "البداري", nameEn: "El Badari" },
      { nameAr: "صدفا", nameEn: "Sedfa" },
      { nameAr: "أسيوط الجديدة", nameEn: "New Asyut" },
    ],
  },
  {
    nameAr: "سوهاج",
    nameEn: "Sohag",
    districts: [
      { nameAr: "سوهاج", nameEn: "Sohag City" },
      { nameAr: "أخميم", nameEn: "Akhmim" },
      { nameAr: "جرجا", nameEn: "Girga" },
      { nameAr: "طهطا", nameEn: "Tahta" },
      { nameAr: "طما", nameEn: "Tama" },
      { nameAr: "المراغة", nameEn: "El Maragha" },
      { nameAr: "المنشأة", nameEn: "El Mansha" },
      { nameAr: "دار السلام", nameEn: "Dar El Salam (Sohag)" },
      { nameAr: "ساقلته", nameEn: "Saqultah" },
      { nameAr: "البلينا", nameEn: "El Balyana" },
      { nameAr: "جهينة", nameEn: "Juhaynah" },
    ],
  },
  {
    nameAr: "قنا",
    nameEn: "Qena",
    districts: [
      { nameAr: "قنا", nameEn: "Qena City" },
      { nameAr: "نجع حمادي", nameEn: "Nag Hammadi" },
      { nameAr: "دشنا", nameEn: "Dishna" },
      { nameAr: "قوص", nameEn: "Qus" },
      { nameAr: "قفط", nameEn: "Qift" },
      { nameAr: "نقادة", nameEn: "Naqada" },
      { nameAr: "أبو تشت", nameEn: "Abu Tesht" },
      { nameAr: "فرشوط", nameEn: "Farshut" },
      { nameAr: "الوقف", nameEn: "El Waqf" },
    ],
  },
  {
    nameAr: "الأقصر",
    nameEn: "Luxor",
    districts: [
      { nameAr: "الأقصر", nameEn: "Luxor City" },
      { nameAr: "الكرنك", nameEn: "Karnak" },
      { nameAr: "الطود", nameEn: "El Toud" },
      { nameAr: "إسنا", nameEn: "Esna" },
      { nameAr: "أرمنت", nameEn: "Armant" },
      { nameAr: "البياضية", nameEn: "El Bayadeya" },
      { nameAr: "الزينية", nameEn: "El Zeiniya" },
      { nameAr: "القرنة", nameEn: "El Qurna" },
    ],
  },
  {
    nameAr: "أسوان",
    nameEn: "Aswan",
    districts: [
      { nameAr: "أسوان", nameEn: "Aswan City" },
      { nameAr: "إدفو", nameEn: "Edfu" },
      { nameAr: "كوم أمبو", nameEn: "Kom Ombo" },
      { nameAr: "دراو", nameEn: "Daraw" },
      { nameAr: "نصر النوبة", nameEn: "Nasr El Nuba" },
      { nameAr: "أبو سمبل", nameEn: "Abu Simbel" },
      { nameAr: "السباعية", nameEn: "El Sebaeya" },
    ],
  },
  {
    nameAr: "البحر الأحمر",
    nameEn: "Red Sea",
    districts: [
      { nameAr: "الغردقة", nameEn: "Hurghada" },
      { nameAr: "رأس غارب", nameEn: "Ras Ghareb" },
      { nameAr: "سفاجا", nameEn: "Safaga" },
      { nameAr: "القصير", nameEn: "El Quseir" },
      { nameAr: "مرسى علم", nameEn: "Marsa Alam" },
      { nameAr: "الشلاتين", nameEn: "Shalateen" },
    ],
  },
  {
    nameAr: "الوادي الجديد",
    nameEn: "New Valley",
    districts: [
      { nameAr: "الخارجة", nameEn: "El Kharga" },
      { nameAr: "الداخلة", nameEn: "El Dakhla" },
      { nameAr: "الفرافرة", nameEn: "El Farafra" },
      { nameAr: "باريس", nameEn: "Paris" },
      { nameAr: "بلاط", nameEn: "Balat" },
    ],
  },
  {
    nameAr: "مطروح",
    nameEn: "Matrouh",
    districts: [
      { nameAr: "مرسى مطروح", nameEn: "Marsa Matrouh" },
      { nameAr: "الحمام", nameEn: "El Hammam" },
      { nameAr: "العلمين", nameEn: "El Alamein" },
      { nameAr: "الضبعة", nameEn: "El Dabaa" },
      { nameAr: "سيدي براني", nameEn: "Sidi Barrani" },
      { nameAr: "سيوة", nameEn: "Siwa" },
      { nameAr: "النجيلة", nameEn: "El Negila" },
    ],
  },
  {
    nameAr: "شمال سيناء",
    nameEn: "North Sinai",
    districts: [
      { nameAr: "العريش", nameEn: "El Arish" },
      { nameAr: "الشيخ زويد", nameEn: "Sheikh Zuwayed" },
      { nameAr: "رفح", nameEn: "Rafah" },
      { nameAr: "بئر العبد", nameEn: "Bir El Abd" },
      { nameAr: "الحسنة", nameEn: "El Hasana" },
      { nameAr: "نخل", nameEn: "Nakhl" },
    ],
  },
  {
    nameAr: "جنوب سيناء",
    nameEn: "South Sinai",
    districts: [
      { nameAr: "شرم الشيخ", nameEn: "Sharm El Sheikh" },
      { nameAr: "دهب", nameEn: "Dahab" },
      { nameAr: "نويبع", nameEn: "Nuweiba" },
      { nameAr: "طابا", nameEn: "Taba" },
      { nameAr: "سانت كاترين", nameEn: "Saint Catherine" },
      { nameAr: "أبو رديس", nameEn: "Abu Rudeis" },
      { nameAr: "أبو زنيمة", nameEn: "Abu Zenima" },
      { nameAr: "الطور", nameEn: "El Tor" },
      { nameAr: "رأس سدر", nameEn: "Ras Sudr" },
    ],
  },
];
